psql postgres postgres
DROP DATABASE IF EXISTS REST;

CREATE DATABASE REST
	WITH ENCODING='UTF8';

exit
psql rest postgres

-- TABLA PROVEEDOR
CREATE TABLE PROVEEDOR
(
	-- PRIMARY KEY
	ID_PROVEEDOR INTEGER PRIMARY KEY,

	-- INFO
	NOMBRE TEXT NOT NULL,
	TELEFONO BIGINT NOT NULL,
	DIRECCION TEXT NOT NULL,
	ESTATUS BOOLEAN DEFAULT TRUE
);

-- EXAMPLES
INSERT INTO PROVEEDOR VALUES(0, 'DEFAULT', 0, 'DEFAULT', DEFAULT);
INSERT INTO PROVEEDOR VALUES(1, 'Lala', 0, 'DEFAULT', DEFAULT);
INSERT INTO PROVEEDOR VALUES(2, 'SuKarne', 0, 'DEFAULT', DEFAULT);
INSERT INTO PROVEEDOR VALUES(3, 'Abarrores', 0, 'DEFAULT', DEFAULT);

-- TABLA EMPLEADO
CREATE TABLE EMPLEADO
(
	-- PRIMARY KEY
	ID_EMPLEADO INTEGER PRIMARY KEY,

	-- INFO
	NOMBRE TEXT NOT NULL,
	CONTRASENA TEXT NOT NULL,
	TELEFONO BIGINT NOT NULL,
	PUESTO TEXT NOT NULL,
	SUELDO INTEGER NOT NULL,
	TELEFONO_EMERGENCIA BIGINT NOT NULL,
	ESTATUS BOOLEAN DEFAULT TRUE
);

-- EXAMPLES
INSERT INTO EMPLEADO VALUES(0, 'DEFAULT', 'DEFAULT', 0, 'DEFAULT', 0, 0, DEFAULT);

-- TABLA INSUMO
CREATE TABLE INSUMO
(
	-- PRIMARY KEY
	ID_INSUMO INTEGER PRIMARY KEY,

	-- INFO
	NOMBRE TEXT NOT NULL,
	DESCRIPCION TEXT NOT NULL,
	EXISTENCIAS INTEGER NOT NULL ,
	FECHA_CADUCIDAD DATE NOT NULL,
	ESTATUS BOOLEAN DEFAULT TRUE
);

-- EXAMPLES
INSERT INTO INSUMO VALUES(0, 'DEFAULT', 'DEFAULT', 0, '1999-01-29', DEFAULT);

-- TABLA INSUMO_PROVEEDOR
CREATE TABLE INSUMO_PROVEEDOR
(
	-- PRIMARY KEY
	ID_INSUMO_PROVEEDOR INTEGER PRIMARY KEY,

	-- FOREIGN KEY
	FK_PROVEEDOR INTEGER REFERENCES PROVEEDOR (ID_PROVEEDOR),
	FK_INSUMO INTEGER REFERENCES INSUMO (ID_INSUMO)
);

-- EXAMPLES
INSERT INTO INSUMO_PROVEEDOR VALUES(0, 0, 0);

